### ISSUE TITLE
Feedback for “Quickstart – OAS Tools”

### ISSUE THREAD

**Issue by cll023** [oas-tools/oas-tools.github.io#21] opened 2022-12-07 03:06 UTC
I am testing with the following open spec

---
openapi: 3.0.2
info:
  title: OAS Tool Test TEST
  description: test purpose
  version: 0.1.0

servers:
  - url: http://localhost:3002/v1
    description: YOUR PODS EXPOSED IP

tags:
  - name: Logging
    description: Service used to change or retrieve current log level

paths:
  /logLevel:
    post:
      tags:
        - logging
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestDocument'
      responses:
        '200':
          description: >-
            After setting the log level, a `logLevel` is returned to indicate the new
            log level.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogLevelResponse'
      operationId: postLogLevel
      x-router-controller: Logging
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    TestDocument:
      type: object
      required:
      - version
      - id
      properties:
        version:
          description: Schema version
          type: string
          pattern: "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$"
          minLength: 3
          maxLength: 11
        id:
          description: Unique ID
          type: string
          example: 1234567
        site:
          type: object
          required:
          - id
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
              minLength: 1
              maxLength: 256
    LogLevelResponse:
      description: Desired logging level response
      type: object
      properties:
        status:
          type: string
          enum:
            - Success
            - Fail
          example: Success
        data:
          type: object
          properties:
            logLevel:
              $ref: '#/components/schemas/LogLevel'
      required:
        - status
        - data
    LogLevel:
      type: string
      enum:
        - fatal
        - error
        - warn
        - info
        - debug
        - trace
      example:
        - 'debug'

Here is my main program:
const express = require("express");
const http = require("http");
const path = require("path");
const oasTools = require("@oas-tools/core");

//
// Local Modules
//

//
// Globals
//
const app = express();

    // Trust first proxy
    app.set("trust proxy", 1);

    // Add session middleware
    // WebProxy.initializeSessions();

    // Handler for incoming HTTP JSON bodies
    app.use(
      express.json({
        strict: true,
        type: "application/json",
        limit: "1mb",
      })
    );
    app.use(
      express.urlencoded({
        extended: true,
        limit: "1mb",
      })
    );

    // The Swagger document (require it, build it programmatically, fetch it from a URL, ...)
    // const spec = fs.readFileSync(
    //   path.join(__dirname, "api/oas-file.yaml"),
    //   "utf8"
    // );
    // const oasDoc = jsyaml.load(spec);
    //
    // // Swagger stats
    // app.use(
    //   swStats.getMiddleware({
    //     metricsPrefix: "search_ingest_",
    //     name: "search_ingest",
    //     swaggerSpec: oasDoc,
    //     uriPath: `/swagger-stats`,
    //   })
    // );

    // OAS-Tools configuration
    const optionsObj = {
      oasFile: path.join(__dirname, "api/oas-file.yaml"),
      logger: {
        level: "debug",
        logFile: false,
      },
      middleware: {
        router: {
          controllers: path.join(__dirname, "/controllers"),
          disable: false,
          requestValidation: true,
          responseValidation: true,
        },
        swagger: {
          path: "/docs",
        },
        security: {
          disable: true,
        },
        validator: {
          strict: true,
          requestValidation: true,
          responseValidation: true,
        },
      },
    }
      // Initialize the OAS middleware
      oasTools.initialize(app, optionsObj).then(() => {
        http.createServer(app).listen(4000, () => {
          console.log(
            `REST API Successfully initialized at port 4000`
          );

      });
  })

And with that if I send in the following POST request with the following body:
{
        "version": "1.3.2",
        "id": "-1068032319"
}

I got the 400 Bad request with the following body:
{
    "error": "RequestValidationError: Request body does not match the schema specified in the OAS Document:\n- Validation failed at #/properties/site/required > must have required property 'id'"
}

It failed to recognize that site is not required.  When I trace the program, it looks like that after
schema.parseBody in OASParams, an empty json object is added to site. Thus it failed schema validation.

**Comment by alesancor1** [comment] 2023-03-04 00:07
Wrong repo, duplicate of https://github.com/oas-tools/oas-tools/issues/356

**Closed by alesancor1** 2023-03-04 00:07 UTC
Labels: duplicate
